server:
  port: 9001
  servlet:
    context-path: /myWeb

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bjpowernode?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: "050614"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lixianda.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
